language: node_js
node_js: node
cache: npm

env:
  global:
    - CODECOV_TOKEN="335481de-068b-4de9-9f8d-137fc39c1e0c"

script:
  - npm run build
after_script:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json